<!--
     @file menu.inc
     
     @brief HTML que como pieza del menú principal es insertado en
     todos los archivos .html del sitio web
     
     @ingroup Frontend
     
     @author Alejandro Salamanca <alejandro@devenet.net>
     @author Virginia Kama <virginia@devenet.net>
     @author Josué Gutiérrez Quino <jgutierrez@devenet.net>
     @author Javier Ramiro Castillo Tarqui <jcastillo@devenet.net>

 
     This file is part of the indicadores-municipales distribution
     (https://fam.egob.org or
     https://github.com/DevenetSRL/indicadores).
     Copyright (c) 2019 Devenet SRL.

     This program is free software: you can redistribute it and/or modify  
     it under the terms of the GNU General Public License as published by  
     the Free Software Foundation, version 3.

     This program is distributed in the hope that it will be useful, but 
     WITHOUT ANY WARRANTY; without even the implied warranty of 
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
     General Public License for more details.

     You should have received a copy of the GNU General Public License 
     along with this program. If not, see <http://www.gnu.org/licenses/>.
-->
<li><a href="javascript:mostrarContenido()"><i class="material-icons">home</i></a></li>
<li><a href="#">Acerca de</a></li>
<li><a href="fichas.html">Fichas</a></li>
<li><a href="#">Municipios</a></li>
